#!/usr/bin/env bash
#
# set -x;
set -e;
set -o pipefail;
#
thisFile="$(readlink -f ${0})";
thisFilePath="$(dirname ${thisFile})";

hostName="${1}";
noIp="${2}";

if [ -z "${hostName}" ]; then
cat << EOF
Usage: ${0} <hostname> [options]

This script is a ssh-keyscan wrapper that outputs yaml to be used in the ansible-ssh-keys role.

Options:
  --no-ip  Do not add the hosts ip address to the '- hostname: ' part
EOF
exit 1;
fi

ipAddress="$(nslookup ${hostName} | awk '/^Address: / { print $2 }')";
ssh-keyscan "${hostName}" 2> /dev/null | while read -r line; do
  if [ "${noIp}" = '--no-ip' ]; then
    echo "  - hostname: '${hostName}'";
  else
    echo "  - hostname: '${hostName} ${ipAddress}'";
  fi
  echo "    enctype: $(echo ${line} | awk '{ print $2 }')";
  echo "    fingerprint: '$(echo ${line} | awk '{ print $3 }')'";
done
