# tasks file
---
- name: authorized-keys | set up for users
  authorized_key:
    user: "{{ item.owner }}"
    key: "{{ lookup('file', item.src) }}"
    state: "{{ item.state | default('present') }}"
    path: "{{ item.path | default('~' + item.owner + '/' + ssh_keys_sshdir + '/authorized_keys') }}"
  with_items: "{{ ssh_keys_authorized_keys }}"
  tags:
    ssh-keys-authorized-keys-setup
