# tasks file for ssh-keys
---
- name: filter users with authorized_keys attribute
  set_fact:
    ssh_keys_users_with_authorized_keys: "{{ ssh_keys_users | selectattr('authorized_keys', 'defined') | list }}"
  tags: [configuration, ssh-keys, ssh-keys-authorized-keys]

- name: set up authorized_keys for users
  authorized_key:
    user: "{{ item.0.owner }}"
    key: "{{ lookup('file', item.1.src) }}"
    state: "{{ item.1.state | default('present') }}"
  with_subelements:
    - ssh_keys_users_with_authorized_keys
    - authorized_keys
  tags: [configuration, ssh-keys, ssh-keys-authorized-keys]
