# tasks file for ssh-keys
---
- name: authorized-keys | set up for users
  authorized_key:
    user: "{{ item.owner }}"
    key: "{{ lookup('file', item.src) }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ ssh_keys_authorized_keys }}"
  tags:
    ssh-keys-authorized-keys-setup
