# tasks file for ssh-keys
---
- include_tasks: general.yml
  tags:
    - configuration
    - ssh-keys
    - ssh-keys-general

- include_tasks: private-keys.yml
  tags:
    - configuration
    - ssh-keys
    - ssh-keys-private-keys

- include_tasks: public-keys.yml
  tags:
    - configuration
    - ssh-keys
    - ssh-keys-public-keys

- include_tasks: authorized-keys.yml
  tags:
    - configuration
    - ssh-keys
    - ssh-keys-authorized-keys

- include_tasks: known-hosts.yml
  tags:
    - configuration
    - ssh-keys
    - ssh-keys-known-hosts
